@startuml
'https://plantuml.com/class-diagram

class BookDTO{
    private int id;
    private String author;
    private String title;
    private Date date;
    private String state;

    public String gets();
    public void sets();
}

class UserDTO{
    private int id;
    private String code;
    private String password;
    private int yearsOld;
    private String firstName;
    private String lastName;
    private String email;
    private String phone;
    private String address;

    public String gets();
    public void sets();
}

class BookReturnDTO {
    private int id;
    private BookDTO bookID;
    private UserDTO userID;
    private Date returnDate;

    public String gets();
    public void sets();
}

class BookLoanDTO {
    private int id;
    private UserDTO userId;
    private BookDTO bookId;
    private Date dateLoan;

    public String gets();
    public void sets();
}

@enduml